<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class AdditionalInformationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('additional_informations')->insert([
            [
                'product_id' => 1,
                'material' => 'Cotton',
                'style' => 'Casual',
                'properties' => 'Round Neck, Breathable, Short Sleeve',
                'brand_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 2,
                'material' => 'Cotton Blend',
                'style' => 'Casual',
                'properties' => 'Graphic Print, Lightweight, Soft Fabric',
                'brand_id' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 3,
                'material' => 'Fleece',
                'style' => 'Winter Wear',
                'properties' => 'Warm, Hooded, Comfortable Fit',
                'brand_id' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 4,
                'material' => 'Cotton Blend',
                'style' => 'Casual',
                'properties' => 'Zipper Closure, Soft Fabric',
                'brand_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 5,
                'material' => 'Cotton',
                'style' => 'Casual',
                'properties' => 'Lightweight, Flexible, Breathable',
                'brand_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 6,
                'material' => 'Cotton',
                'style' => 'Fashion',
                'properties' => 'Printed Design, Soft Touch',
                'brand_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 7,
                'material' => 'Polyester Blend',
                'style' => 'Summer Wear',
                'properties' => 'Floral Print, Lightweight',
                'brand_id' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 8,
                'material' => 'Polyester',
                'style' => 'Formal',
                'properties' => 'Straight Fit, Comfortable',
                'brand_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 9,
                'material' => 'Genuine Leather',
                'style' => 'Premium',
                'properties' => 'Multiple Card Slots, Durable',
                'brand_id' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 10,
                'material' => 'Nylon',
                'style' => 'Travel',
                'properties' => 'Laptop Compartment, Spacious Storage',
                'brand_id' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 11,
                'material' => 'Premium Cotton',
                'style' => 'Casual',
                'properties' => 'Striped Pattern, Crew Neck, Breathable',
                'brand_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 12,
                'material' => 'Fleece',
                'style' => 'Winter Wear',
                'properties' => 'Warm Fabric, Hooded, Soft Touch',
                'brand_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 13,
                'material' => 'Polyester Blend',
                'style' => 'Sports Wear',
                'properties' => 'Quick Dry, Lightweight, Stretchable',
                'brand_id' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 14,
                'material' => 'Cotton',
                'style' => 'Casual',
                'properties' => 'Embroidered Design, Soft Fabric',
                'brand_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 15,
                'material' => 'Premium Blend',
                'style' => 'Party Wear',
                'properties' => 'A-Line Design, Elegant Finish',
                'brand_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 16,
                'material' => 'Polyester',
                'style' => 'Formal',
                'properties' => 'Office Wear, Tailored Fit',
                'brand_id' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 17,
                'material' => 'Denim',
                'style' => 'Casual',
                'properties' => 'Comfort Fit, Durable Fabric',
                'brand_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 18,
                'material' => 'Genuine Leather',
                'style' => 'Premium',
                'properties' => 'RFID Protection, Multiple Card Slots',
                'brand_id' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 19,
                'material' => 'Genuine Leather',
                'style' => 'Formal',
                'properties' => 'Adjustable Buckle, Durable',
                'brand_id' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 20,
                'material' => 'Silver Plated Alloy',
                'style' => 'Fashion',
                'properties' => 'Pendant Design, Lightweight',
                'brand_id' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 21,
                'material' => 'Premium Cotton',
                'style' => 'Casual',
                'properties' => 'Polo Collar, Breathable Fabric',
                'brand_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 22,
                'material' => 'Cotton Blend',
                'style' => 'Winter Wear',
                'properties' => 'Full Sleeve, Hooded Design',
                'brand_id' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 23,
                'material' => 'Polyester Blend',
                'style' => 'Sports Wear',
                'properties' => 'Quick Dry, Lightweight',
                'brand_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 24,
                'material' => 'Cotton',
                'style' => 'Casual',
                'properties' => 'Graphic Print, Soft Texture',
                'brand_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 25,
                'material' => 'Rayon',
                'style' => 'Party Wear',
                'properties' => 'Elegant Design, Lightweight',
                'brand_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 26,
                'material' => 'Cotton Blend',
                'style' => 'Formal',
                'properties' => 'Comfort Fit, Breathable',
                'brand_id' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 27,
                'material' => 'Polyester',
                'style' => 'Sports Wear',
                'properties' => 'Stretchable, Quick Dry',
                'brand_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 28,
                'material' => 'Polyester',
                'style' => 'Travel',
                'properties' => 'Water Resistant, Large Capacity',
                'brand_id' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 29,
                'material' => 'Genuine Leather',
                'style' => 'Formal',
                'properties' => 'Premium Buckle, Durable',
                'brand_id' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 30,
                'material' => 'Alloy',
                'style' => 'Fashion',
                'properties' => 'Handcrafted, Lightweight',
                'brand_id' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 31,
                'material' => 'Cotton',
                'style' => 'Casual',
                'properties' => 'Round Neck, Comfortable',
                'brand_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 32,
                'material' => 'Fleece',
                'style' => 'Winter Wear',
                'properties' => 'Warm Fabric, Pullover',
                'brand_id' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 33,
                'material' => 'Polyester Blend',
                'style' => 'Sports Wear',
                'properties' => 'Flexible, Lightweight',
                'brand_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 34,
                'material' => 'Cotton',
                'style' => 'Casual',
                'properties' => 'Printed Pattern, Soft Fabric',
                'brand_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 35,
                'material' => 'Rayon',
                'style' => 'Party Wear',
                'properties' => 'Elegant Finish, Comfortable',
                'brand_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 36,
                'material' => 'Linen Blend',
                'style' => 'Formal',
                'properties' => 'Wrinkle Resistant, Premium Look',
                'brand_id' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 37,
                'material' => 'Denim',
                'style' => 'Casual',
                'properties' => 'Durable Fabric, Slim Fit',
                'brand_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 38,
                'material' => 'Polyester',
                'style' => 'Travel',
                'properties' => 'Multiple Compartments, Water Resistant',
                'brand_id' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 39,
                'material' => 'Genuine Leather',
                'style' => 'Premium',
                'properties' => 'Classic Design, Durable',
                'brand_id' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 40,
                'material' => 'Silver Plated Alloy',
                'style' => 'Fashion',
                'properties' => 'Elegant Pendant, Lightweight',
                'brand_id' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 41,
                'material' => 'Cotton',
                'style' => 'Casual',
                'properties' => 'Breathable, Soft Touch',
                'brand_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 42,
                'material' => 'Cotton Blend',
                'style' => 'Casual',
                'properties' => 'Printed Design, Lightweight',
                'brand_id' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 43,
                'material' => 'Fleece',
                'style' => 'Winter Wear',
                'properties' => 'Warm, Hooded, Comfortable',
                'brand_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 44,
                'material' => 'Polyester',
                'style' => 'Sports Wear',
                'properties' => 'Quick Dry, Stretchable',
                'brand_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 45,
                'material' => 'Denim',
                'style' => 'Casual',
                'properties' => 'Slim Fit, Durable Fabric',
                'brand_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 46,
                'material' => 'Rayon',
                'style' => 'Party Wear',
                'properties' => 'Elegant Finish, Lightweight',
                'brand_id' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 47,
                'material' => 'Linen',
                'style' => 'Formal',
                'properties' => 'Premium Look, Wrinkle Resistant',
                'brand_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 48,
                'material' => 'Polyester',
                'style' => 'Travel',
                'properties' => 'Water Resistant, Spacious',
                'brand_id' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 49,
                'material' => 'Leather',
                'style' => 'Premium',
                'properties' => 'Durable, Luxury Finish',
                'brand_id' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 50,
                'material' => 'Alloy',
                'style' => 'Fashion',
                'properties' => 'Lightweight, Stylish Design',
                'brand_id' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 51,
                'material' => 'Premium Cotton',
                'style' => 'Casual',
                'properties' => 'Crew Neck, Comfortable Fit',
                'brand_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 52,
                'material' => 'Cotton Blend',
                'style' => 'Winter Wear',
                'properties' => 'Full Sleeve, Warm Fabric',
                'brand_id' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 53,
                'material' => 'Polyester Blend',
                'style' => 'Sports Wear',
                'properties' => 'Flexible, Lightweight',
                'brand_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 54,
                'material' => 'Cotton',
                'style' => 'Casual',
                'properties' => 'Graphic Print, Soft Fabric',
                'brand_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 55,
                'material' => 'Rayon',
                'style' => 'Party Wear',
                'properties' => 'Elegant Pattern, Comfortable',
                'brand_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 56,
                'material' => 'Linen Blend',
                'style' => 'Formal',
                'properties' => 'Premium Finish, Wrinkle Resistant',
                'brand_id' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 57,
                'material' => 'Denim',
                'style' => 'Casual',
                'properties' => 'Comfort Fit, Durable Stitching',
                'brand_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 58,
                'material' => 'Polyester',
                'style' => 'Travel',
                'properties' => 'Large Capacity, Water Resistant',
                'brand_id' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 59,
                'material' => 'Genuine Leather',
                'style' => 'Premium',
                'properties' => 'Classic Design, Long Lasting',
                'brand_id' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 60,
                'material' => 'Silver Plated Alloy',
                'style' => 'Fashion',
                'properties' => 'Elegant Look, Lightweight',
                'brand_id' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 61,
                'material' => 'Cotton',
                'style' => 'Casual',
                'properties' => 'Round Neck, Breathable Fabric',
                'brand_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 62,
                'material' => 'Cotton Blend',
                'style' => 'Casual',
                'properties' => 'Soft Touch, Regular Fit',
                'brand_id' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 63,
                'material' => 'Fleece',
                'style' => 'Winter Wear',
                'properties' => 'Warm Fabric, Hooded Design',
                'brand_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 64,
                'material' => 'Polyester',
                'style' => 'Sports Wear',
                'properties' => 'Quick Dry, Lightweight',
                'brand_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 65,
                'material' => 'Denim',
                'style' => 'Casual',
                'properties' => 'Durable Fabric, Slim Fit',
                'brand_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 66,
                'material' => 'Rayon',
                'style' => 'Party Wear',
                'properties' => 'Elegant Design, Soft Feel',
                'brand_id' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 67,
                'material' => 'Linen',
                'style' => 'Formal',
                'properties' => 'Wrinkle Resistant, Premium Look',
                'brand_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 68,
                'material' => 'Polyester',
                'style' => 'Travel',
                'properties' => 'Water Resistant, Large Capacity',
                'brand_id' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 69,
                'material' => 'Leather',
                'style' => 'Premium',
                'properties' => 'Luxury Finish, Durable',
                'brand_id' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 70,
                'material' => 'Alloy',
                'style' => 'Fashion',
                'properties' => 'Modern Design, Lightweight',
                'brand_id' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 71,
                'material' => 'Premium Cotton',
                'style' => 'Casual',
                'properties' => 'Crew Neck, Comfortable Fit',
                'brand_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 72,
                'material' => 'Cotton Blend',
                'style' => 'Winter Wear',
                'properties' => 'Full Sleeve, Soft Fabric',
                'brand_id' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 73,
                'material' => 'Polyester Blend',
                'style' => 'Sports Wear',
                'properties' => 'Stretchable, Sweat Absorbent',
                'brand_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 74,
                'material' => 'Cotton',
                'style' => 'Casual',
                'properties' => 'Printed Design, Lightweight',
                'brand_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 75,
                'material' => 'Rayon',
                'style' => 'Party Wear',
                'properties' => 'Elegant Finish, Comfortable',
                'brand_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 76,
                'material' => 'Linen Blend',
                'style' => 'Formal',
                'properties' => 'Premium Fabric, Breathable',
                'brand_id' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 77,
                'material' => 'Denim',
                'style' => 'Casual',
                'properties' => 'Slim Fit, Durable Stitching',
                'brand_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 78,
                'material' => 'Polyester',
                'style' => 'Travel',
                'properties' => 'Multiple Compartments, Water Resistant',
                'brand_id' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 79,
                'material' => 'Genuine Leather',
                'style' => 'Premium',
                'properties' => 'Classic Design, Long Lasting',
                'brand_id' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 80,
                'material' => 'Silver Plated Alloy',
                'style' => 'Fashion',
                'properties' => 'Stylish Pendant, Lightweight',
                'brand_id' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 81,
                'material' => 'Cotton',
                'style' => 'Casual',
                'properties' => 'Breathable Fabric, Round Neck',
                'brand_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 82,
                'material' => 'Cotton Blend',
                'style' => 'Casual',
                'properties' => 'Soft Texture, Regular Fit',
                'brand_id' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 83,
                'material' => 'Fleece',
                'style' => 'Winter Wear',
                'properties' => 'Hooded Design, Warm Fabric',
                'brand_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 84,
                'material' => 'Polyester',
                'style' => 'Sports Wear',
                'properties' => 'Quick Dry, Lightweight',
                'brand_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 85,
                'material' => 'Denim',
                'style' => 'Casual',
                'properties' => 'Slim Fit, Durable Stitching',
                'brand_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 86,
                'material' => 'Rayon',
                'style' => 'Party Wear',
                'properties' => 'Elegant Finish, Comfortable',
                'brand_id' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 87,
                'material' => 'Linen',
                'style' => 'Formal',
                'properties' => 'Wrinkle Resistant, Premium Look',
                'brand_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 88,
                'material' => 'Polyester',
                'style' => 'Travel',
                'properties' => 'Large Capacity, Water Resistant',
                'brand_id' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 89,
                'material' => 'Leather',
                'style' => 'Premium',
                'properties' => 'Luxury Finish, Durable',
                'brand_id' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 90,
                'material' => 'Alloy',
                'style' => 'Fashion',
                'properties' => 'Modern Design, Lightweight',
                'brand_id' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 91,
                'material' => 'Premium Cotton',
                'style' => 'Casual',
                'properties' => 'Crew Neck, Soft Fabric',
                'brand_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 92,
                'material' => 'Cotton Blend',
                'style' => 'Winter Wear',
                'properties' => 'Full Sleeve, Comfortable',
                'brand_id' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 93,
                'material' => 'Polyester Blend',
                'style' => 'Sports Wear',
                'properties' => 'Stretchable, Sweat Absorbent',
                'brand_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 94,
                'material' => 'Cotton',
                'style' => 'Casual',
                'properties' => 'Printed Design, Lightweight',
                'brand_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 95,
                'material' => 'Rayon',
                'style' => 'Party Wear',
                'properties' => 'Elegant Design, Comfortable',
                'brand_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 96,
                'material' => 'Linen Blend',
                'style' => 'Formal',
                'properties' => 'Premium Fabric, Breathable',
                'brand_id' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 97,
                'material' => 'Denim',
                'style' => 'Casual',
                'properties' => 'Comfort Fit, Durable',
                'brand_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 98,
                'material' => 'Polyester',
                'style' => 'Travel',
                'properties' => 'Multiple Compartments, Water Resistant',
                'brand_id' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 99,
                'material' => 'Genuine Leather',
                'style' => 'Premium',
                'properties' => 'Classic Design, Long Lasting',
                'brand_id' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 100,
                'material' => 'Silver Plated Alloy',
                'style' => 'Fashion',
                'properties' => 'Elegant Pendant, Lightweight',
                'brand_id' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
