<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'collection_id' => 1,
                'brand_id' => 1,
                'name' => 'Men Round Neck Cotton T-Shirt',
                'description' => 'Premium cotton t-shirt with a comfortable fit, ideal for everyday casual wear.',
                'base_price' => 799,
                'image_url' => 'img/shirt.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 1,
                'brand_id' => 2,
                'name' => 'Men Graphic Print T-Shirt',
                'description' => 'Stylish graphic print t-shirt crafted from breathable fabric for all-day comfort.',
                'base_price' => 899,
                'image_url' => 'img/shirt-black.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 2,
                'brand_id' => 8,
                'name' => 'Men Solid Pullover Hoodie',
                'description' => 'Warm and comfortable hoodie designed for outdoor adventures and daily use.',
                'base_price' => 1499,
                'image_url' => 'img/hoodie-man-3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 2,
                'brand_id' => 4,
                'name' => 'Men Zipper Hoodie',
                'description' => 'Modern zip-up hoodie with premium fabric and a sleek contemporary design.',
                'base_price' => 1699,
                'image_url' => 'img/hoodie-man-4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 3,
                'brand_id' => 3,
                'name' => 'Men Casual Cotton Shorts',
                'description' => 'Lightweight cotton shorts offering comfort and flexibility for daily activities.',
                'base_price' => 699,
                'image_url' => 'img/men-shorts-1.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 4,
                'brand_id' => 5,
                'name' => 'Women Printed Cotton T-Shirt',
                'description' => 'Trendy printed t-shirt made with soft cotton fabric for comfort and style.',
                'base_price' => 849,
                'image_url' => 'img/women-T-shirts-1.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 5,
                'brand_id' => 6,
                'name' => 'Women Floral Summer Dress',
                'description' => 'Elegant floral dress designed with lightweight fabric for a graceful look.',
                'base_price' => 1999,
                'image_url' => 'img/women-dress-1.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 6,
                'brand_id' => 7,
                'name' => 'Women Straight Fit Pants',
                'description' => 'Comfortable straight-fit pants suitable for office wear and casual outings.',
                'base_price' => 1299,
                'image_url' => 'img/women-pant-1.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 8,
                'brand_id' => 9,
                'name' => 'Premium Leather Wallet',
                'description' => 'Genuine leather wallet featuring multiple card slots and a timeless design.',
                'base_price' => 2499,
                'image_url' => 'img/wallet-2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 9,
                'brand_id' => 10,
                'name' => 'Laptop Travel Backpack',
                'description' => 'Durable backpack with a padded laptop compartment and spacious storage.',
                'base_price' => 1799,
                'image_url' => 'img/backpack-9.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'collection_id' => 1,
                'brand_id' => 3,
                'name' => 'Men Striped Crew Neck T-Shirt',
                'description' => 'Classic striped t-shirt crafted from premium cotton for a stylish casual look.',
                'base_price' => 949,
                'image_url' => 'img/shirt-green.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 2,
                'brand_id' => 1,
                'name' => 'Men Fleece Winter Hoodie',
                'description' => 'Soft fleece hoodie designed to provide exceptional warmth during colder days.',
                'base_price' => 1899,
                'image_url' => 'img/hoodie-man-4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 3,
                'brand_id' => 8,
                'name' => 'Men Sports Training Shorts',
                'description' => 'Performance-focused shorts with breathable fabric for workouts and outdoor activities.',
                'base_price' => 899,
                'image_url' => 'img/men-shorts-5.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 4,
                'brand_id' => 7,
                'name' => 'Women Embroidered Cotton T-Shirt',
                'description' => 'Elegant embroidered t-shirt featuring soft fabric and a comfortable fit.',
                'base_price' => 999,
                'image_url' => 'img/women-T-shirts-3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 5,
                'brand_id' => 5,
                'name' => 'Women A-Line Midi Dress',
                'description' => 'Stylish A-line dress designed with premium fabric for a sophisticated appearance.',
                'base_price' => 2299,
                'image_url' => 'img/women-dress-2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 6,
                'brand_id' => 6,
                'name' => 'Women Formal Office Pants',
                'description' => 'Tailored formal pants offering a sleek fit and all-day comfort for workwear.',
                'base_price' => 1499,
                'image_url' => 'img/women-pant-2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 7,
                'brand_id' => 5,
                'name' => 'Women Denim Casual Shorts',
                'description' => 'Modern denim shorts designed for comfort, style, and everyday wear.',
                'base_price' => 1099,
                'image_url' => 'img/women-shorts-1.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 8,
                'brand_id' => 9,
                'name' => 'RFID Protected Leather Wallet',
                'description' => 'Premium leather wallet with RFID protection to keep your cards secure.',
                'base_price' => 2799,
                'image_url' => 'img/wallet-2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 10,
                'brand_id' => 2,
                'name' => 'Classic Brown Leather Belt',
                'description' => 'Elegant genuine leather belt designed to complement formal and business attire.',
                'base_price' => 1199,
                'image_url' => 'img/belt-3.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 11,
                'brand_id' => 10,
                'name' => 'Silver Plated Pendant Necklace',
                'description' => 'Contemporary pendant necklace featuring a sleek design for everyday elegance.',
                'base_price' => 1599,
                'image_url' => 'img/Necklaces-1.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'collection_id' => 1,
                'brand_id' => 4,
                'name' => 'Men Premium Polo T-Shirt',
                'description' => 'Premium polo t-shirt featuring a modern fit, breathable fabric, and timeless style.',
                'base_price' => 1199,
                'image_url' => 'img/shirt-red.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 2,
                'brand_id' => 2,
                'name' => 'Men Cotton Blend Hoodie',
                'description' => 'Stylish cotton blend hoodie offering warmth, comfort, and a contemporary look.',
                'base_price' => 1799,
                'image_url' => 'img/hoodie-man-2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 3,
                'brand_id' => 1,
                'name' => 'Men Relaxed Fit Lounge Shorts',
                'description' => 'Comfortable lounge shorts made from soft fabric, perfect for casual wear.',
                'base_price' => 799,
                'image_url' => 'img/men-shorts-3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 4,
                'brand_id' => 6,
                'name' => 'Women Graphic Print T-Shirt',
                'description' => 'Fashionable graphic print t-shirt designed to add a trendy touch to your wardrobe.',
                'base_price' => 899,
                'image_url' => 'img/women-T-shirts-3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 5,
                'brand_id' => 7,
                'name' => 'Women Ethnic Printed Dress',
                'description' => 'Beautiful ethnic-inspired dress crafted with premium fabric and elegant detailing.',
                'base_price' => 2499,
                'image_url' => 'img/women-dress-3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 6,
                'brand_id' => 5,
                'name' => 'Women Cotton Palazzo Pants',
                'description' => 'Lightweight palazzo pants offering superior comfort and effortless style.',
                'base_price' => 1399,
                'image_url' => 'img/women-pant-3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 7,
                'brand_id' => 6,
                'name' => 'Women Running Shorts',
                'description' => 'Performance running shorts designed with breathable material for active lifestyles.',
                'base_price' => 999,
                'image_url' => 'img/women-shorts-2.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 9,
                'brand_id' => 8,
                'name' => 'Adventure Hiking Backpack',
                'description' => 'Rugged backpack with multiple compartments, ideal for trekking and travel.',
                'base_price' => 2999,
                'image_url' => 'img/backpack-2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 10,
                'brand_id' => 9,
                'name' => 'Premium Formal Leather Belt',
                'description' => 'Crafted from genuine leather, this belt delivers durability and sophisticated style.',
                'base_price' => 1499,
                'image_url' => 'img/belt-6.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 11,
                'brand_id' => 7,
                'name' => 'Designer Beaded Necklace',
                'description' => 'Handcrafted beaded necklace featuring an elegant design for festive occasions.',
                'base_price' => 1899,
                'image_url' => 'img/Necklaces-10.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'collection_id' => 1,
                'brand_id' => 1,
                'name' => 'Men Solid Crew Neck T-Shirt',
                'description' => 'A versatile crew neck t-shirt crafted from premium cotton for everyday comfort and style.',
                'base_price' => 749,
                'image_url' => 'img/shirt.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 1,
                'brand_id' => 2,
                'name' => 'Men Premium V-Neck T-Shirt',
                'description' => 'Elegant V-neck t-shirt featuring a tailored fit and superior fabric quality.',
                'base_price' => 999,
                'image_url' => 'img/shirt-green.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 2,
                'brand_id' => 8,
                'name' => 'Men Outdoor Adventure Hoodie',
                'description' => 'Durable hoodie designed for outdoor activities with exceptional comfort and warmth.',
                'base_price' => 2199,
                'image_url' => 'img/hoodie-man-3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 3,
                'brand_id' => 3,
                'name' => 'Men Athletic Performance Shorts',
                'description' => 'Breathable performance shorts engineered for sports, training, and active lifestyles.',
                'base_price' => 949,
                'image_url' => 'img/men-shorts-4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 4,
                'brand_id' => 5,
                'name' => 'Women Casual Everyday T-Shirt',
                'description' => 'Comfortable cotton t-shirt designed to complement both casual and semi-casual outfits.',
                'base_price' => 799,
                'image_url' => 'img/women-T-shirts-4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 5,
                'brand_id' => 6,
                'name' => 'Women Floral Maxi Dress',
                'description' => 'Elegant floral maxi dress featuring a flowing silhouette and lightweight fabric.',
                'base_price' => 2799,
                'image_url' => 'img/women-dress-4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 6,
                'brand_id' => 7,
                'name' => 'Women Relaxed Fit Cotton Pants',
                'description' => 'Soft cotton pants offering a relaxed fit and exceptional comfort throughout the day.',
                'base_price' => 1599,
                'image_url' => 'img/women-pant-4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 8,
                'brand_id' => 9,
                'name' => 'Vintage Leather Wallet',
                'description' => 'Handcrafted leather wallet with a vintage finish and spacious card compartments.',
                'base_price' => 2899,
                'image_url' => 'img/wallet-3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 9,
                'brand_id' => 10,
                'name' => 'Urban Commuter Backpack',
                'description' => 'Modern backpack with dedicated laptop storage and multiple utility pockets.',
                'base_price' => 2099,
                'image_url' => 'img/backpack-9.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 11,
                'brand_id' => 7,
                'name' => 'Traditional Pearl Necklace',
                'description' => 'Beautiful pearl necklace inspired by traditional craftsmanship and timeless elegance.',
                'base_price' => 2299,
                'image_url' => 'img/Necklaces-9.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'collection_id' => 1,
                'brand_id' => 4,
                'name' => 'Men Slim Fit Polo T-Shirt',
                'description' => 'Premium slim-fit polo t-shirt crafted with breathable fabric for a refined casual look.',
                'base_price' => 1099,
                'image_url' => 'img/shirt-red.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 2,
                'brand_id' => 1,
                'name' => 'Men Casual Zip-Up Hoodie',
                'description' => 'Comfortable zip-up hoodie featuring soft fleece lining and a modern design.',
                'base_price' => 1899,
                'image_url' => 'img/hoodie-man-2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 3,
                'brand_id' => 8,
                'name' => 'Men Cargo Utility Shorts',
                'description' => 'Durable cargo shorts with multiple pockets, perfect for outdoor adventures.',
                'base_price' => 1199,
                'image_url' => 'img/men-shorts-5.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 4,
                'brand_id' => 6,
                'name' => 'Women Floral Print T-Shirt',
                'description' => 'Stylish floral print t-shirt made from soft cotton fabric for everyday comfort.',
                'base_price' => 899,
                'image_url' => 'img/women-T-shirts-4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 5,
                'brand_id' => 5,
                'name' => 'Women Sleeveless Summer Dress',
                'description' => 'Elegant sleeveless dress designed for warm weather and effortless style.',
                'base_price' => 2399,
                'image_url' => 'img/women-dress-5.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 6,
                'brand_id' => 7,
                'name' => 'Women Linen Straight Pants',
                'description' => 'Premium linen pants offering exceptional comfort and a sophisticated appearance.',
                'base_price' => 1699,
                'image_url' => 'img/women-pant-5.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 7,
                'brand_id' => 5,
                'name' => 'Women High Rise Denim Shorts',
                'description' => 'Fashionable high-rise shorts crafted from durable denim with a flattering fit.',
                'base_price' => 1299,
                'image_url' => 'img/women-shorts-3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 8,
                'brand_id' => 9,
                'name' => 'Executive Leather Wallet',
                'description' => 'Sophisticated leather wallet featuring premium craftsmanship and ample storage.',
                'base_price' => 3199,
                'image_url' => 'img/wallet-4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 10,
                'brand_id' => 2,
                'name' => 'Black Formal Leather Belt',
                'description' => 'Classic black leather belt designed to complement professional and formal attire.',
                'base_price' => 1399,
                'image_url' => 'img/belt-3.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 11,
                'brand_id' => 10,
                'name' => 'Crystal Pendant Necklace',
                'description' => 'Elegant crystal pendant necklace designed to enhance both casual and festive outfits.',
                'base_price' => 1999,
                'image_url' => 'img/Necklaces-4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'collection_id' => 1,
                'brand_id' => 3,
                'name' => 'Men Henley Neck T-Shirt',
                'description' => 'Classic Henley neck t-shirt made from premium cotton with a comfortable regular fit.',
                'base_price' => 999,
                'image_url' => 'img/shirt-black.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 2,
                'brand_id' => 4,
                'name' => 'Men Oversized Streetwear Hoodie',
                'description' => 'Trendy oversized hoodie featuring a relaxed fit and ultra-soft fabric.',
                'base_price' => 2199,
                'image_url' => 'img/hoodie-man-2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 3,
                'brand_id' => 1,
                'name' => 'Men Drawstring Cotton Shorts',
                'description' => 'Comfortable cotton shorts with an adjustable waistband for all-day wear.',
                'base_price' => 899,
                'image_url' => 'img/men-shorts-1.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 4,
                'brand_id' => 7,
                'name' => 'Women V-Neck Printed T-Shirt',
                'description' => 'Soft cotton V-neck t-shirt featuring elegant prints and a flattering fit.',
                'base_price' => 949,
                'image_url' => 'img/women-T-shirts-6.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 5,
                'brand_id' => 6,
                'name' => 'Women Embroidered Maxi Dress',
                'description' => 'Beautiful embroidered maxi dress crafted for special occasions and festive wear.',
                'base_price' => 2999,
                'image_url' => 'img/women-dress-1.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 6,
                'brand_id' => 5,
                'name' => 'Women Ankle Length Trousers',
                'description' => 'Elegant ankle-length trousers offering a modern silhouette and superior comfort.',
                'base_price' => 1599,
                'image_url' => 'img/women-pant-1.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 7,
                'brand_id' => 6,
                'name' => 'Women Cotton Lounge Shorts',
                'description' => 'Relaxed-fit lounge shorts made from breathable cotton fabric for maximum comfort.',
                'base_price' => 799,
                'image_url' => 'img/women-shorts-4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 9,
                'brand_id' => 8,
                'name' => 'Water Resistant Travel Backpack',
                'description' => 'Durable water-resistant backpack with spacious compartments for travel and daily use.',
                'base_price' => 2599,
                'image_url' => 'img/backpack-4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 10,
                'brand_id' => 9,
                'name' => 'Tan Genuine Leather Belt',
                'description' => 'Premium tan leather belt handcrafted for durability and timeless style.',
                'base_price' => 1699,
                'image_url' => 'img/belt-4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 11,
                'brand_id' => 10,
                'name' => 'Rose Gold Charm Necklace',
                'description' => 'Elegant rose gold necklace featuring stylish charms and a contemporary design.',
                'base_price' => 2199,
                'image_url' => 'img/Necklaces-5.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'collection_id' => 1,
                'brand_id' => 1,
                'name' => 'Men Premium Cotton Henley T-Shirt',
                'description' => 'Crafted from soft premium cotton, this Henley t-shirt offers a stylish look and superior comfort.',
                'base_price' => 1099,
                'image_url' => 'img/shirt.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 2,
                'brand_id' => 8,
                'name' => 'Men Thermal Winter Hoodie',
                'description' => 'Insulated thermal hoodie designed to keep you warm during cold weather adventures.',
                'base_price' => 2499,
                'image_url' => 'img/hoodie-man-2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 3,
                'brand_id' => 3,
                'name' => 'Men Quick Dry Sports Shorts',
                'description' => 'Lightweight quick-dry shorts built for workouts, jogging, and outdoor activities.',
                'base_price' => 999,
                'image_url' => 'img/men-shorts-3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 4,
                'brand_id' => 5,
                'name' => 'Women Relaxed Fit Graphic T-Shirt',
                'description' => 'Trendy graphic t-shirt featuring a relaxed fit and breathable cotton fabric.',
                'base_price' => 949,
                'image_url' => 'img/women-T-shirts-6.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 5,
                'brand_id' => 6,
                'name' => 'Women Printed Boho Dress',
                'description' => 'Beautiful bohemian-inspired dress with vibrant prints and a flowing silhouette.',
                'base_price' => 2699,
                'image_url' => 'img/women-dress-2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 6,
                'brand_id' => 7,
                'name' => 'Women High Waist Linen Pants',
                'description' => 'Elegant linen pants designed with a high-waist fit for modern styling and comfort.',
                'base_price' => 1799,
                'image_url' => 'img/women-pant-2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 7,
                'brand_id' => 5,
                'name' => 'Women Stretch Denim Shorts',
                'description' => 'Comfortable stretch denim shorts offering flexibility and a flattering fit.',
                'base_price' => 1199,
                'image_url' => 'img/women-shorts-5.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 8,
                'brand_id' => 9,
                'name' => 'Classic Bifold Leather Wallet',
                'description' => 'Sophisticated bifold wallet handcrafted from genuine leather with ample storage.',
                'base_price' => 2999,
                'image_url' => 'img/wallet-2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 9,
                'brand_id' => 10,
                'name' => 'Smart Laptop Office Backpack',
                'description' => 'Modern office backpack featuring a padded laptop sleeve and multiple organizer pockets.',
                'base_price' => 2399,
                'image_url' => 'img/backpack-5.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 11,
                'brand_id' => 7,
                'name' => 'Handcrafted Ethnic Necklace',
                'description' => 'Traditional handcrafted necklace designed to complement ethnic and festive outfits.',
                'base_price' => 2499,
                'image_url' => 'img/Necklaces-6.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'collection_id' => 8,
                'brand_id' => 9,
                'name' => 'Premium RFID Leather Wallet',
                'description' => 'Elegant RFID-blocking wallet crafted from genuine leather to keep your essentials secure.',
                'base_price' => 3299,
                'image_url' => 'img/wallet-3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 8,
                'brand_id' => 9,
                'name' => 'Compact Card Holder Wallet',
                'description' => 'Slim and lightweight wallet designed for carrying cards and cash with ease.',
                'base_price' => 1899,
                'image_url' => 'img/wallet-4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 8,
                'brand_id' => 10,
                'name' => 'Urban Casual Wallet',
                'description' => 'Modern wallet featuring a sleek design and multiple compartments for daily use.',
                'base_price' => 1499,
                'image_url' => 'img/wallet-3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 9,
                'brand_id' => 8,
                'name' => 'Mountain Trekking Backpack',
                'description' => 'Spacious trekking backpack with ergonomic straps and multiple storage compartments.',
                'base_price' => 3499,
                'image_url' => 'img/backpack-6.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 9,
                'brand_id' => 10,
                'name' => 'College Everyday Backpack',
                'description' => 'Stylish everyday backpack suitable for college, office, and short trips.',
                'base_price' => 1799,
                'image_url' => 'img/backpack-2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 9,
                'brand_id' => 8,
                'name' => 'Multi-Purpose Travel Backpack',
                'description' => 'Durable travel backpack featuring water-resistant material and spacious storage.',
                'base_price' => 2899,
                'image_url' => 'img/backpack-8.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 10,
                'brand_id' => 2,
                'name' => 'Reversible Leather Belt',
                'description' => 'Premium reversible belt offering two stylish looks in one sophisticated accessory.',
                'base_price' => 1699,
                'image_url' => 'img/belt-5.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 10,
                'brand_id' => 9,
                'name' => 'Textured Brown Leather Belt',
                'description' => 'Handcrafted leather belt with a textured finish for a refined and elegant appearance.',
                'base_price' => 1899,
                'image_url' => 'img/belt-6.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 11,
                'brand_id' => 7,
                'name' => 'Antique Beaded Necklace',
                'description' => 'Beautiful handcrafted necklace featuring antique beads and traditional artistry.',
                'base_price' => 2299,
                'image_url' => 'img/Necklaces-7.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 11,
                'brand_id' => 10,
                'name' => 'Minimalist Chain Necklace',
                'description' => 'Contemporary chain necklace designed for everyday elegance and modern fashion.',
                'base_price' => 1799,
                'image_url' => 'img/Necklaces-1.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'collection_id' => 1,
                'brand_id' => 4,
                'name' => 'Men Melange Cotton T-Shirt',
                'description' => 'Stylish melange cotton t-shirt designed for superior comfort and a modern casual look.',
                'base_price' => 1149,
                'image_url' => 'img/shirt-red.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 2,
                'brand_id' => 8,
                'name' => 'Men Activewear Training Hoodie',
                'description' => 'Performance hoodie with moisture-wicking fabric, ideal for workouts and outdoor activities.',
                'base_price' => 2299,
                'image_url' => 'img/hoodie-man-2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 3,
                'brand_id' => 1,
                'name' => 'Men Relaxed Cargo Shorts',
                'description' => 'Comfortable cargo shorts featuring spacious pockets and durable cotton construction.',
                'base_price' => 1249,
                'image_url' => 'img/men-shorts-3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 4,
                'brand_id' => 5,
                'name' => 'Women Floral Graphic T-Shirt',
                'description' => 'Elegant floral graphic t-shirt crafted from soft fabric for all-day comfort.',
                'base_price' => 999,
                'image_url' => 'img/women-T-shirts-1.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 5,
                'brand_id' => 6,
                'name' => 'Women Tiered Maxi Dress',
                'description' => 'Beautiful tiered maxi dress featuring a graceful silhouette and premium fabric.',
                'base_price' => 3199,
                'image_url' => 'img/women-dress-3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 6,
                'brand_id' => 7,
                'name' => 'Women Tapered Fit Pants',
                'description' => 'Smart tapered-fit pants combining comfort, elegance, and versatility.',
                'base_price' => 1899,
                'image_url' => 'img/women-pant-3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 8,
                'brand_id' => 9,
                'name' => 'Luxury Executive Wallet',
                'description' => 'Premium executive wallet handcrafted from genuine leather with elegant detailing.',
                'base_price' => 3599,
                'image_url' => 'img/wallet-2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 9,
                'brand_id' => 10,
                'name' => 'Business Laptop Backpack',
                'description' => 'Professional laptop backpack with padded compartments and smart organization features.',
                'base_price' => 2699,
                'image_url' => 'img/backpack-4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 10,
                'brand_id' => 2,
                'name' => 'Premium Formal Buckle Belt',
                'description' => 'Elegant leather belt featuring a premium metallic buckle and superior craftsmanship.',
                'base_price' => 1799,
                'image_url' => 'img/belt-4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 11,
                'brand_id' => 7,
                'name' => 'Handcrafted Tribal Necklace',
                'description' => 'Unique handcrafted necklace inspired by traditional tribal art and culture.',
                'base_price' => 2599,
                'image_url' => 'img/Necklaces-9.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'collection_id' => 1,
                'brand_id' => 2,
                'name' => 'Men Everyday Essential T-Shirt',
                'description' => 'A versatile everyday t-shirt crafted from premium cotton for lasting comfort and style.',
                'base_price' => 899,
                'image_url' => 'img/shirt-green.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 2,
                'brand_id' => 4,
                'name' => 'Men Premium Fleece Hoodie',
                'description' => 'Soft fleece hoodie designed to provide warmth, comfort, and a contemporary look.',
                'base_price' => 2399,
                'image_url' => 'img/hoodie-man-2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 3,
                'brand_id' => 3,
                'name' => 'Men Weekend Casual Shorts',
                'description' => 'Relaxed-fit shorts perfect for weekend outings, vacations, and casual wear.',
                'base_price' => 1099,
                'image_url' => 'img/men-shorts-4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 4,
                'brand_id' => 6,
                'name' => 'Women Stylish Round Neck T-Shirt',
                'description' => 'Modern round-neck t-shirt featuring a comfortable fit and elegant design.',
                'base_price' => 999,
                'image_url' => 'img/women-T-shirts-1.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 5,
                'brand_id' => 5,
                'name' => 'Women Elegant Evening Dress',
                'description' => 'Sophisticated evening dress crafted with premium fabric for special occasions.',
                'base_price' => 3499,
                'image_url' => 'img/women-dress-4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 6,
                'brand_id' => 7,
                'name' => 'Women Comfort Fit Cotton Pants',
                'description' => 'Soft cotton pants offering a relaxed fit and exceptional all-day comfort.',
                'base_price' => 1699,
                'image_url' => 'img/women-pant-5.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 8,
                'brand_id' => 9,
                'name' => 'Premium Travel Wallet',
                'description' => 'Spacious leather travel wallet designed to securely store cards, cash, and documents.',
                'base_price' => 3799,
                'image_url' => 'img/wallet-3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 9,
                'brand_id' => 8,
                'name' => 'Expedition Trek Backpack',
                'description' => 'Heavy-duty trekking backpack with ergonomic support and multiple storage compartments.',
                'base_price' => 3999,
                'image_url' => 'img/backpack-9.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 10,
                'brand_id' => 9,
                'name' => 'Handcrafted Vintage Leather Belt',
                'description' => 'Premium handcrafted leather belt featuring a vintage finish and durable construction.',
                'base_price' => 1999,
                'image_url' => 'img/belt-5.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'collection_id' => 11,
                'brand_id' => 10,
                'name' => 'Elegant Stone Pendant Necklace',
                'description' => 'Beautiful stone pendant necklace designed to elevate both casual and festive outfits.',
                'base_price' => 2299,
                'image_url' => 'img/Necklaces-10.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
